apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: astronomy-app
  namespace: argocd

spec:
  project: astronomy-project
  source:
    repoURL: https://github.com/siddheshengineer/Astronomy-Shop---Fullstack-DevOps.git
    targetRevision: LKE             # ← now tracking LKE branch
    path: astronomy-helmcharts      # path to Helm chart in the repo
    helm: 
      valueFiles:
        - values.yaml

  destination:
    namespace: astronomy
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
    # syncOptions:
    #   - CreateNamespace=true        # auto-create the “astronomy” namespace if needed