# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argocd-ingress
#   namespace: argocd
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: "/$1"
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: astronomy.siddheshnikam.online
#       http:
#         paths:
#           - pathType: ImplementationSpecific
#             path: "/argocd(/|$)(.*)"
#             backend:
#               service:
#                 name: argocd-server
#                 port:
#                   number: 80
