name: Astronomy CI Pipeline

# ────── Triggers ────────────────────────────────────────────────
on:
  push:
    branches: ['main', 'LKE']
    paths:
      - 'src/**'
  pull_request:
    branches: ['main', 'LKE']
    paths:
        - 'src/**' 

# ────── Global Permissions ────────────────────────────────────────
permissions:
  contents: read
  packages: write
  security-events: write

# ────── Jobs ──────────────────────────────────────────────────────
jobs:
# ────── Job 1 ─────────────────────────────────────────────────────
  get_changed_folder:
    name: Getting updated Service 
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      count: ${{ steps.set-matrix.outputs.count }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Changed Folder
        id: changed-folder
        uses: tj-actions/changed-files@v46
        with:
          since_last_remote_commit: true
        
      - name: Matrix
        id: set-matrix
        shell: bash
        run: |
          # Create array for changed folders in '/src'
          mapfile -t services < <(
            printf '%s\n' "${{ steps.changed-folder.outputs.all_changed_files }}" |
            tr ' ' '\n' |
            grep '^src/' |
            awk -F/ '{print $2}' |
            sort -u
          )

          # Convert to JSON array
          json=$(printf '%s\n' "${services[@]}" | jq -R -s -c 'split("\n")[:-1]')

          # outputs
          echo "matrix={\"service\":$json}" >>"$GITHUB_OUTPUT"
          echo "count=$(echo "$json" | jq 'length')" >>"$GITHUB_OUTPUT"
          echo #####
          echo "Services changed: ${services[*]}"
          echo "No. of changed services: $(echo "$json" | jq 'length')"
      
      # - name: No. of Changes services
      #   run: |
      #     echo "${{ steps.set-matrix.outputs.count }}"

# ────── Job 2 ─────────────────────────────────────────────────────
  build_container_images:
    name: Build container images 
    runs-on: ubuntu-latest
    needs: [get_changed_folder]
    if: ${{ fromJson(needs.get_changed_folder.output.matrix).service != [] }} # skip if nothing has changed

    strategy:
      fail-fast: true
      matrix: 
        value: ${{ fromJson(needs.get_changed_folder.output.matrix) }}
    
    env:
      REGISTRY: docker.io
      DOCKER_USER: ${{ secrets.REG_USER }}
      DOCKER_REPO: ${{ secrets.CONTAINER_REPOSITORY_NAME }} 
      CONTAINER_REPO: ${{ env.REGISTRY }}/${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_TOKEN }}  

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src/${{ matrix.service }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:${{ github.run_number }}-${{ matrix.service }}
          load: true





      
    
