name: Astronomy CI Pipeline

# ────── Triggers ────────────────────────────────────────────────
on:
  push:
    branches: ['main', 'LKE']
    paths:
      - 'src/**'
  pull_request:
    branches: ['main', 'LKE']
    paths:
        - 'src/**' 

# ────── Global Permissions ────────────────────────────────────────
permissions:
  contents: read
  packages: write
  security-events: write

# ────── Jobs ──────────────────────────────────────────────────────
jobs:
# ────── Jobs 1 ────────────────────────────────────────────────────
  get_changed_folder:
    name: Getting updated Service 
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      count: ${{ steps.set-matrix.outputs.count }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Changed Folder
        id: changed-folder
        uses: tj-actions/changed-files@v46
        with:
          since_last_remote_commit: true
        
      - name: Matrix
        id: set-matrix
        shell: bash
        run: |
          # Create array for changed folders in '/src'
          makefile -t services < <(
            printf '%s\n' "${{ steps.changed-folder.outputs.all_changed_files }}" \
            tr ',' '\n'
            grep '^src/'
            awk -F/ '{print $2}'
            sort -u
          )

          # Build a Json object of the array
          json=$(print '%s\n' "${services[@]}") | jq -R -s -c 'split("\n")[:-1]'

          # outputs
          echo "matrix={\"service\":$json}" >> "$GITHUB_OUTPUT"
          echo "count=$(echo "$json" | jq 'length')" >> "$GITHUB_OUTPUT"





      
    
